version: "3.8"

services:

  postgresql:
    image: postgres
    container_name: sns-test-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sns
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - /var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: sns-test-zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: sns-test-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS : "alarm:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:latest
    container_name: sns-test-redis
    ports:
      - "6379:6379"

  gonue-sns-server:
    container_name: gonue-sns-app
    build: .
    depends_on:
      - sns-test-postgres
      - sns-test-zookeeper
      - sns-test-kafka
      - sns-test-redis
    image: gonue/application-server
    ports:
      - "8080:8080"
    restart: always



